version: '3'
services:
  server:
    build: ./server
    ports:
      - '3000:3000'
    depends_on:
      - client
    environment:
      - NODE_ENV=production
  client:
    build: ./client
    ports:
      - '1234:1234'
    environment:
      - NODE_ENV=production