version: '3'
services:
  server:
    build: ./server
    ports:
      - '3000:3000'
    depends_on:
      - client
    env_file:
      - ./server/.env

  client:
    build: ./client
    ports:
      - '1234:1234'
    env_file:
      - ./client/.env
